import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
// import styles from "@/styles/Home.module.css";
import dynamic from "next/dynamic";
import { useState } from "react";
// import CustomEditor from "@/components/CustomEditor";
const CustomEditor = dynamic(() => import("@/components/CustomEditor"), {
  ssr: false,
});
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [data, setData] = useState("<h1>Heading</h1><p>Some text</p>");
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CustomEditor data={data} setData={setData} />
    </>
  );
}
